### ISSUE TITLE
https connection timeout

### ISSUE THREAD

**Issue by tomonariokubo** [nikolaykasyanov/xmlrpc#13]
Thanks for the really useful library.
I'm trying to connect to my wordpress website from app.

There is no problem when I use 'http://example.com/xmlrpc.php' as endpoint but after I changed to 'https://example.com/xmlrpc.php', connection always gets time out.
I can access to the https url via web browser and says 'XML-RPC server accepts POST requests only.'

Do I need to fix client side code or change server configuration?

My code is like below: 

    var request1: XMLRPCRequest = XMLRPCRequest(URL:"https://example.com/xmlrpc.php")
    request1.setMethod("country.list", withParameters: [lastSyncDateTime])
    manager.spawnConnectionWithXMLRPCRequest(request1, delegate: self)

I appreciate any suggestions.

**Comment by corristo** [comment]
Hi, could you please send exact NSError that happens when you use HTTPS? Thanks!

**Comment by nikolaykasyanov** [comment]
This library is discontinued.
