### ISSUE TITLE
Leak of XMLRPCConnection objects on non-ARC path?

### ISSUE THREAD

**Issue by psulak** [nikolaykasyanov/xmlrpc#7]
Hi XMLRPC Guys -

First off, thanks for maintaining this Framework:-)

We'd been using an older build of XMLRPC from January, 2012. After we updated it to the latest code, we started noticing that certain objects in our application weren't getting released, and eventually tracked the problem to XMLRPCConnection.

In older versions of the framework, the XMLRPCConnection objects were always released in [XMLRPCConnection connectionDidFinishLoading:] by virtue of calling [XMLRPCConnectionManager closeConnectionForIdentifier:]. When the ARC conversion was done to the Framework, the call to closeConnectionForIdentifier was initially left out, but then put back into the ARC path at a later date (see the commit on Oct 12, 2012).

However, our application is non-ARC, and once we updated to the latest version of the Framework, the XMLRPCConnection objs stopped being released (and thus caused leaks). We "fixed" the problem on our end by simply adding back the call [XMLRPCConnectionManager closeConnectionForIdentifier:] to the non-ARC path. So now we're trying to determine if this was just an oversight in the ARC conversion of the framework, or a purposeful change in functionality. If anyone can offer some insight on this, it'd be a big help.

Thanks!

**Comment by nikolaykasyanov** [comment]
This library is discontinued.
